#!/usr/bin/env python3
"""
Parse ipc_payloads.bin generated by Steam API Proxy IPC dump module (V2).

Usage:
    python parse_ipc_dump.py ipc_payloads.bin
    python parse_ipc_dump.py ipc_payloads.bin --json
    python parse_ipc_dump.py ipc_payloads.bin --filter C         # Callbacks only
    python parse_ipc_dump.py ipc_payloads.bin --filter R         # CallResults only
    python parse_ipc_dump.py ipc_payloads.bin --callback 1101    # Specific callback ID
    python parse_ipc_dump.py ipc_payloads.bin --extract-dir ./packets
    python parse_ipc_dump.py ipc_payloads.bin --stats

Binary record format V2 (little-endian):
    [4B magic 0x53544D50 "STMP"]
    [8B timestamp_us]
    [4B thread_id]
    [4B callback_id]
    [1B type - 'C'=callback, 'R'=callresult, 'D'=dispatch]
    [1B flags - 0x80=failed for callresults]
    [2B reserved]
    [4B payload_size]
    [NB payload]
    [4B crc32]
"""

import struct
import sys
import os
import json
import argparse
from binascii import crc32 as calc_crc32


FILE_HEADER_SIZE = 16
RECORD_MAGIC = 0x53544D50
RECORD_HEADER_FMT = "<I Q I I B B H I"
RECORD_HEADER_SIZE = struct.calcsize(RECORD_HEADER_FMT)

# Known callback names
CALLBACK_NAMES = {
    101: "SteamServersConnected_t",
    102: "SteamServerConnectFailure_t",
    103: "SteamServersDisconnected_t",
    113: "ClientGameServerDeny_t",
    115: "IPCFailure_t",
    117: "LicensesUpdated_t",
    143: "GameLobbyJoinRequested_t",
    154: "GetAuthSessionTicketResponse_t",
    163: "ValidateAuthTicketResponse_t",
    164: "MicroTxnAuthorizationResponse_t",
    165: "EncryptedAppTicketResponse_t",
    166: "GetTicketForWebApiResponse_t",
    168: "GameRichPresenceJoinRequested_t",
    304: "LobbyDataUpdate_t",
    305: "LobbyChatUpdate_t",
    306: "LobbyChatMsg_t",
    309: "LobbyMatchList_t",
    331: "FriendRichPresenceUpdate_t",
    333: "FavoritesListChanged_t",
    336: "LobbyCreated_t",
    337: "LobbyEnter_t",
    338: "LobbyInvite_t",
    342: "PersonaStateChange_t",
    343: "GameOverlayActivated_t",
    348: "AvatarImageLoaded_t",
    502: "IPCountry_t",
    504: "P2PSessionRequest_t",
    505: "P2PSessionConnectFail_t",
    506: "SocketStatusCallback_t",
    512: "LobbyGameCreated_t",
    701: "SteamAPICallCompleted_t",
    703: "GamepadTextInputDismissed_t",
    704: "ScreenshotReady_t",
    736: "AppResumingFromSuspend_t",
    1005: "DlcInstalled_t",
    1101: "UserStatsReceived_t",
    1102: "UserStatsStored_t",
    1103: "UserAchievementStored_t",
    1108: "UserStatsUnloaded_t",
    1109: "UserAchievementIconFetched_t",
    1201: "SteamNetworkingMessagesSessionRequest_t",
    1202: "SteamNetConnectionStatusChangedCallback_t",
    1203: "SteamNetAuthenticationStatus_t",
    1221: "SteamRelayNetworkStatus_t",
    1307: "RemoteStoragePublishFileProgress_t",
    1309: "RemoteStoragePublishedFileUpdated_t",
    2801: "SteamInputDeviceConnected_t",
    2802: "SteamInputDeviceDisconnected_t",
    3401: "SteamUGCQueryCompleted_t",
    3402: "SteamUGCRequestUGCDetailsResult_t",
    3403: "CreateItemResult_t",
    3404: "SubmitItemUpdateResult_t",
    3405: "ItemInstalled_t",
    3406: "DownloadItemResult_t",
}

TYPE_NAMES = {
    ord('C'): 'CALLBACK',
    ord('R'): 'CALLRESULT',
    ord('D'): 'DISPATCH',
}


def hex_dump(data, max_bytes=128, indent=4):
    prefix = " " * indent
    lines = []
    show = min(len(data), max_bytes)
    for offset in range(0, show, 16):
        chunk = data[offset:offset+16]
        hex_part = " ".join(f"{b:02X}" for b in chunk)
        ascii_part = "".join(chr(b) if 0x20 <= b < 0x7F else "." for b in chunk)
        lines.append(f"{prefix}{offset:08X}  {hex_part:<48s}  |{ascii_part}|")
    if len(data) > max_bytes:
        lines.append(f"{prefix}... ({len(data) - max_bytes} more bytes)")
    return "\n".join(lines)


def try_decode_utf8(data):
    try:
        s = data.decode("utf-8", errors="strict")
        printable = sum(1 for c in s if c.isprintable() or c in "\r\n\t")
        if len(s) > 0 and printable > len(s) * 0.7:
            return s
    except:
        pass
    return None


def parse_protobuf_like(data):
    """Naive protobuf varint field parsing."""
    fields = []
    pos = 0
    try:
        while pos < len(data) and len(fields) < 32:
            tag = 0
            shift = 0
            while pos < len(data):
                b = data[pos]; pos += 1
                tag |= (b & 0x7F) << shift; shift += 7
                if not (b & 0x80): break

            field_num = tag >> 3
            wire_type = tag & 0x07
            if field_num == 0 or field_num > 65536: break

            if wire_type == 0:
                val = 0; shift = 0
                while pos < len(data):
                    b = data[pos]; pos += 1
                    val |= (b & 0x7F) << shift; shift += 7
                    if not (b & 0x80): break
                fields.append((field_num, "varint", val))
            elif wire_type == 1:
                if pos + 8 > len(data): break
                val = struct.unpack_from("<Q", data, pos)[0]; pos += 8
                fields.append((field_num, "fixed64", val))
            elif wire_type == 2:
                length = 0; shift = 0
                while pos < len(data):
                    b = data[pos]; pos += 1
                    length |= (b & 0x7F) << shift; shift += 7
                    if not (b & 0x80): break
                if length > len(data) - pos or length > 1024*1024: break
                raw = data[pos:pos+length]; pos += length
                s = try_decode_utf8(raw)
                fields.append((field_num, "string" if s else "bytes",
                               s[:200] if s else raw[:64].hex()))
            elif wire_type == 5:
                if pos + 4 > len(data): break
                val = struct.unpack_from("<I", data, pos)[0]; pos += 4
                fields.append((field_num, "fixed32", val))
            else:
                break
    except:
        pass
    return fields if len(fields) >= 2 else None


def parse_file(filepath, args):
    with open(filepath, "rb") as f:
        header = f.read(FILE_HEADER_SIZE)
        if not header.startswith(b"STMP_IPC_DUMP_V"):
            print(f"Warning: unexpected file header: {header!r}")
            f.seek(0)

        records = []
        record_idx = 0

        while True:
            hdr_data = f.read(RECORD_HEADER_SIZE)
            if len(hdr_data) < RECORD_HEADER_SIZE:
                break

            magic, ts_us, tid, cb_id, rtype, flags, reserved, payload_size = \
                struct.unpack(RECORD_HEADER_FMT, hdr_data)

            if magic != RECORD_MAGIC:
                print(f"[!] Bad magic at offset {f.tell() - RECORD_HEADER_SIZE}: 0x{magic:08X}")
                break
            if payload_size > 16 * 1024 * 1024:
                print(f"[!] Suspicious payload size: {payload_size}")
                break

            payload = f.read(payload_size)
            if len(payload) < payload_size:
                print(f"[!] Truncated payload at record {record_idx}")
                break

            crc_data = f.read(4)
            if len(crc_data) < 4:
                print(f"[!] Truncated CRC at record {record_idx}")
                break

            stored_crc = struct.unpack("<I", crc_data)[0]
            computed_crc = calc_crc32(payload) & 0xFFFFFFFF

            record = {
                "index": record_idx,
                "timestamp_us": ts_us,
                "timestamp_ms": ts_us / 1000.0,
                "thread_id": tid,
                "callback_id": cb_id,
                "callback_name": CALLBACK_NAMES.get(cb_id),
                "type": chr(rtype),
                "type_name": TYPE_NAMES.get(rtype, f"?{rtype}"),
                "flags": flags,
                "failed": bool(flags & 0x80),
                "size": payload_size,
                "crc_ok": stored_crc == computed_crc,
                "payload": payload,
            }

            # Apply filters
            if args.filter and chr(rtype) not in args.filter.upper():
                record_idx += 1; continue
            if args.callback and cb_id != args.callback:
                record_idx += 1; continue
            if args.min_size and payload_size < args.min_size:
                record_idx += 1; continue

            records.append(record)
            record_idx += 1

    return records


def print_records(records, args):
    if args.json:
        output = []
        for r in records:
            entry = {
                "index": r["index"],
                "timestamp_ms": r["timestamp_ms"],
                "thread_id": r["thread_id"],
                "callback_id": r["callback_id"],
                "callback_name": r["callback_name"],
                "type": r["type"],
                "type_name": r["type_name"],
                "failed": r["failed"],
                "size": r["size"],
                "crc_ok": r["crc_ok"],
                "payload_hex": r["payload"][:256].hex(),
            }
            s = try_decode_utf8(r["payload"])
            if s: entry["payload_utf8"] = s[:500]
            pb = parse_protobuf_like(r["payload"])
            if pb:
                entry["protobuf_fields"] = [
                    {"field": f, "type": t, "value": str(v)[:200]} for f, t, v in pb
                ]
            output.append(entry)
        print(json.dumps(output, indent=2, ensure_ascii=False))
        return

    print(f"\n{'='*72}")
    print(f" Steam Callback/IPC Payload Dump — {len(records)} records")
    print(f"{'='*72}\n")

    for r in records:
        name = r["callback_name"] or "unknown"
        print(f"┌─ Record #{r['index']}  ─────────────────────────────────")
        print(f"│ Time: {r['timestamp_ms']:.3f} ms   TID: {r['thread_id']}")
        print(f"│ Callback: {r['callback_id']} ({name})")
        print(f"│ Type: {r['type_name']}  Size: {r['size']}B  "
              f"CRC: {'OK' if r['crc_ok'] else 'MISMATCH!'}"
              f"{'  FAILED!' if r['failed'] else ''}")

        s = try_decode_utf8(r["payload"])
        if s:
            print(f"│ UTF-8: {s[:300]}")

        pb = parse_protobuf_like(r["payload"])
        if pb:
            print(f"│ Protobuf-like ({len(pb)} fields):")
            for fn, wt, v in pb[:16]:
                print(f"│   field {fn:>4} ({wt:>7}): {str(v)[:120]}")

        print(f"│ Hex:")
        print(hex_dump(r["payload"], max_bytes=args.hex_bytes))
        print(f"└{'─'*50}\n")


def extract_payloads(records, output_dir):
    os.makedirs(output_dir, exist_ok=True)
    for r in records:
        name = r["callback_name"] or f"cb{r['callback_id']}"
        fname = f"{r['index']:06d}_{r['type']}_{name}_{r['timestamp_us']}.bin"
        # Sanitize filename
        fname = "".join(c if c.isalnum() or c in "._-" else "_" for c in fname)
        with open(os.path.join(output_dir, fname), "wb") as f:
            f.write(r["payload"])
    print(f"Extracted {len(records)} payloads to {output_dir}/")


def main():
    parser = argparse.ArgumentParser(description="Parse Steam callback/IPC payload dumps")
    parser.add_argument("input", help="Path to ipc_payloads.bin")
    parser.add_argument("--json", action="store_true", help="Output as JSON")
    parser.add_argument("--filter", type=str, default=None,
                        help="Filter by type: C=callback, R=callresult, D=dispatch")
    parser.add_argument("--callback", type=int, default=None,
                        help="Filter by callback ID (e.g. 1101)")
    parser.add_argument("--min-size", type=int, default=0,
                        help="Minimum payload size")
    parser.add_argument("--hex-bytes", type=int, default=128,
                        help="Max bytes in hex dump (default 128)")
    parser.add_argument("--extract-dir", type=str, default=None,
                        help="Extract raw payloads to directory")
    parser.add_argument("--stats", action="store_true",
                        help="Show summary statistics only")

    args = parser.parse_args()
    if not os.path.exists(args.input):
        print(f"Error: {args.input} not found"); sys.exit(1)

    records = parse_file(args.input, args)

    if args.stats:
        print(f"Total records: {len(records)}")
        by_type = {}
        by_cb = {}
        for r in records:
            by_type[r["type_name"]] = by_type.get(r["type_name"], 0) + 1
            by_cb[r["callback_id"]] = by_cb.get(r["callback_id"], 0) + 1

        print("  By type:")
        for t, c in sorted(by_type.items()):
            print(f"    {t}: {c}")

        print(f"  Unique callback IDs: {len(by_cb)}")
        print("  By callback (top 20):")
        for cb_id, cnt in sorted(by_cb.items(), key=lambda x: -x[1])[:20]:
            name = CALLBACK_NAMES.get(cb_id, "unknown")
            print(f"    {cb_id:>5} ({name}): {cnt}")

        total_bytes = sum(r["size"] for r in records)
        crc_fails = sum(1 for r in records if not r["crc_ok"])
        failed = sum(1 for r in records if r["failed"])
        print(f"  Total payload: {total_bytes:,} bytes")
        print(f"  CRC failures: {crc_fails}")
        print(f"  Failed results: {failed}")
        return

    if args.extract_dir:
        extract_payloads(records, args.extract_dir)
    else:
        print_records(records, args)


if __name__ == "__main__":
    main()